version: 1.0
resources:
  - name: PortfolioWebsiteSource
    type: GitHub
    properties:
      Owner: ibhavneshbaghel2213
      Repo: Portfolio-Website
      Branch: main
      # OAuthToken: <GitHub_OAuth_Token>
stages:
  - name: Source
    actions:
      - name: SourceAction
        actionTypeId:
          category: Source
          owner: AWS
          provider: CodeStarSourceConnection
          version: 1
        configuration:
          ConnectionArn: <CodeStar_Connection_ARN>
          FullRepositoryId: ibhavneshbaghel2213/Portfolio-Website
          BranchName: main
        outputArtifacts:
          - name: SourceOutput
  - name: Build
    actions:
      - name: BuildAction
        actionTypeId:
          category: Build
          owner: AWS
          provider: CodeBuild
          version: 1
        inputArtifacts:
          - name: SourceOutput
        configuration:
          ProjectName: sme-testing-jenkins-conversion
  - name: Deploy
    actions:
      - name: DeployToS3
        actionTypeId:
          category: Deploy
          owner: AWS
          provider: S3
          version: 1
        inputArtifacts:
          - name: BuildOutput
        configuration:
          BucketName: hu-edge-assignment
          Extract: true
artifacts:
  files:
    - "**/*"
  discard:
    keep: 10
options:
  timeout: 30
  disableConcurrentBuilds: true
post:
  always:
    - echo: "Pipeline execution completed."
  success:
    - echo: "Build and deployment succeeded."
  failure:
    - echo: "Build or deployment failed."