name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_S3_BUCKET: hu-edge-assignment
      AWS_REGION: us-east-1
      CI: ""
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Upload Artifacts to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp ./build s3://$AWS_S3_BUCKET/ --recursive

      - name: Post Build Actions
        if: always()
        run: echo 'Pipeline execution completed.'

      - name: Success Notification
        if: success()
        run: echo 'Build and deployment succeeded.'

      - name: Failure Notification
        if: failure()
        run: echo 'Build or deployment failed.'
